#ifndef ECALIBRATIONSTATE_H
#define ECALIBRATIONSTATE_H

enum class ECalibrationState {
  START_CALIBRATION,
  TOUCH_TOP_LEFT,
  TOP_LEFT_COUNTDOWN,
  TOUCH_BOTTOM_RIGHT,
  BOTTOM_RIGHT_COUNTDOWN,
  EXIT_CALIBRATION
};

#endif //ECALIBRATIONSTATE_H